# CMake on multiple platforms using CMakePresets
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      # Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        include:
          # Windows preset (Visual Studio 18 2026 generator)
          - os: windows-2025-vs2026
            configure_preset: windows-release
            build_preset: windows-release-build
            test_preset: windows-release-test
          # Linux preset  
          - os: ubuntu-latest
            configure_preset: linux-release
            build_preset: linux-release-build
            test_preset: linux-release-test
            cc: gcc-15
            cxx: g++-15

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC 15
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt update
        sudo apt install -y gcc-15 g++-15

    - name: CMake Configure
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: cmake --preset ${{ matrix.configure_preset }}

    - name: CMake Build
      run: cmake --build --preset ${{ matrix.build_preset }}

    - name: CMake Test
      run: ctest --preset ${{ matrix.test_preset }}
